;LED BLINKING IN THIS PROGRAM WE ARE GOING TO BLINK PORTB LED GLOW


#include<p16f877a.inc> ;HEADER FILE INCLUTION
#define _XTAL_FREQ 20000000
__CONFIG(_CP_OFF&_WDT_OFF &_PWRTE_ON &_HS_OSC);
;__CONFIG(_FOSC_HS &_WDTE_OFF &_PWRTE_OFF &_BOREN_ON &_LVP_OFF);

ORG 00H
GOTO 05H
ORG 05H 			;ORGIN WHERE THE STARTING POINT
;SWITCH TO BANK1  
BSF STATUS,RP0		;RP0 BANK SELECTION BANK 1
BCF STATUS,RP1		;RP1 THIS IS FOR STATUS BIT
;ENABLE PORTB PIN 1 AS A OUTPUT PIN   
MOVLW 0X00			; LITERAL VALUE STORING TO WORKING REGISTER
MOVWF TRISB			; WORKING REGISTER TO FILE REGISTER
;SWITCH TO BANK 0
BCF STATUS,RP0		; SELECTING BANK 0
;SENDING SIGNAL TO PORTB PIN 1
MOVLW 0X01			; LITERAL VALUE STORING TO WORKING REGISTER
MOVWF PORTB			; WORKING REGISTER TO FILE REGISTER
NOP
GOW:
NOP
NOP
	GOTO GOW
END 
